[package]
name = "kernel"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait.workspace = true
shared.workspace = true
anyhow.workspace = true
serde.workspace = true
sqlx.workspace = true
uuid.workspace = true
