[package]
name = "shared"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
strum.workspace = true
axum.workspace = true
thiserror.workspace = true
tracing.workspace = true
sqlx.workspace = true
uuid.workspace = true
